name: GitHub Actions CI

on: [push, pull_request]

jobs:
  tests:
    name: +test +test-fail
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_CONVERSION_PARALLELISM: "5"
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      GHA_FORK_REPO: "${{ github.event.pull_request.head.repo.full_name }}"
      EARTHLY_INSTALL_ID: "earthly-githubactions"
    steps:
      - uses: earthly/actions/setup-earthly@v1
      - uses: actions/checkout@v2
      - name: Print Env
        run: env
