name: GitHub Actions CI


jobs:
  tests:
    name: simple test
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_CONVERSION_PARALLELISM: "5"
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      GHA_FORK_REPO: "${{ github.event.pull_request.head.repo.full_name }}"
      EARTHLY_INSTALL_ID: "earthly-githubactions"
    steps:
      - name: Print Env
        run: env

